CREATE TABLE user (
    id          INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    username    VARCHAR(30) NOT NULL UNIQUE,
    password    VARCHAR(60) NOT NULL,
    email       VARCHAR(50) NOT NULL UNIQUE,
    status      INT,
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
